baseURL = "https://nathanlockwood.github.io"
title = "Nathan Lockwood"
author = "nathanlockwood"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
resourceDir = "../resources"
enableEmoji = true
googleAnalytics = "UA-12345678-1"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]

  showBlog = false
  mainSections = ['services', 'about']
  custom_css = ["/css/index.css"]

  googleFonts = true

  [params.meta]
    favicon = "favicon/favicon.ico"

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Nathan Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Nathan Lockwood"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Nathan Lockwood Electrical & Handyman Services"
    meta_og_title = "Nathan Lockwood"
    meta_og_type = "website"
    meta_og_url = "https://nathan-lockwood.com"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Nathan Lockwood Electrical & Handyman Services"

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 10

  [[menu.footer]]
    name = "(737)382-2693"
    url = "tel:7373822693"
      weight = 2

  [[menu.footer]]
    name = "nat.f.lockwood@gmail.com"
    url = "mailto:nat.f.lockwood@gmail.com"
      weight = 3